plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dost.zikirdua'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dost.zikirdua'
        minSdk 21
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
